# Change these first
owner: sonicspinforum # Your GitHub organization or username, where this repository lives
repo: SonicpediaStatus # The name of this repository

sites:
  - name: 索尼克百科 Sonicpedia
    url: https://sonic.wiki/
  - name: 索尼克百科 Action API
    url: https://sonic.wiki/api.php?action=query&prop=info&titles=Sonic
    method: GET
  - name: 索尼克百科 REST API
    url: https://sonic.wiki/rest.php/v1/page/Sonic
    method: GET
  - name: 索尼克百科 Parsoid
    url: https://sonic.wiki/api.php?action=visualeditor&format=json&paction=parse&page=Sonic
    method: GET
    __dangerous__body_down: "apierror-"

# CI schedule
workflowSchedule:
  # Check for response time every hour
  responseTime: "0 * * * *"
  graphs: "2 * * * *"
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.sonic.wiki
  # baseUrl: /your-repo-name
  favicon: https://sonic.wiki/favicon.ico
  logoUrl: https://sonic.wiki/headlogo.png
  name: 索尼克百科 - 服务状态
  #introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  #introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: 主页
      href: https://sonic.wiki
    - title: 状态
      href: /
  theme: dark
  customHeadHtml: "<style>:root{--body-background-color:#131a21!important;--body-text-color:rgba(255, 255, 255, 0.6)!important;--card-background-color:#282f35!important;--nav-background-color:transparent!important;--nav-border-bottom-color:transparent!important;--nav-current-border-bottom-color:#36c!important;--card-border-color:rgba(255, 255, 255, 0.05)!important;--down-border-left-color:#dd3333!important;--down-background-color:#6b1020!important;--degraded-border-left-color:#ffcc33!important;--up-border-left-color:#00af89!important;--tag-color:#1f262c!important;--tag-up-background-color:#14866d!important;--tag-down-background-color:#b32424!important;--tag-degraded-background-color:#ac6600!important;--change-background-color:#f7b731!important;--error-button-border-color:#1a46ad!important;--error-button-background-color:#3867d6!important;--error-button-color:#ffffff!important;--submit-button-border-color:#1a46ad!important;--submit-button-background-color:#3867d6!important;--submit-button-color:#ffffff!important;--graph-opacity:1!important;--graph-filter:none!important}header.svelte-ngkazm{margin:0}nav.svelte-a08hsz.svelte-a08hsz{margin-bottom:10px;padding:0;font-weight:500}.container{padding:0 20px}.logo.svelte-a08hsz.svelte-a08hsz{padding:1rem 0}.logo.svelte-a08hsz img.svelte-a08hsz{filter:invert(1) hue-rotate(180deg);opacity:.5;transition:opacity 250ms ease}.logo.svelte-a08hsz img.svelte-a08hsz:hover{opacity:.7}.logo.svelte-a08hsz img.svelte-a08hsz:active{opacity:.3}.logo.svelte-a08hsz.svelte-a08hsz>div{display:none}a{transition:opacity 250ms ease}a:hover{opacity:.7}a:active{oapcity:.4}a.svelte-a08hsz.svelte-a08hsz{padding:10px 15px}[aria-current]{border-bottom:0!important;color:var(--nav-current-border-bottom-color)}.r.svelte-14gfn20 label.svelte-14gfn20.svelte-14gfn20{cursor:pointer;font-weight:500}.r.svelte-14gfn20 input.svelte-14gfn20:checked+label.svelte-14gfn20{color:var(--nav-current-border-bottom-color)}</style>"
  #themeUrl: /assets/sct-dark.css (Style from https://github.com/StarCitizenTools/upptime/blob/master/.upptimerc.yml)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
